# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 15 Oct 2017 04:25:49 +0000
*	@user	1
*	@ALL	1
*	@editor	8
*	@moderator	16
design	@ALL	0
design	@editor	1
design	@moderator	2
design:*	@ALL	0
design:*	@user	1
design:*	@editor	1
design:*	@moderator	8
editing	@moderator	1
editing	@editor	1
editing	@user	0
editing:*	@ALL	0
editing:*	@editor	1
editing:*	@moderator	1
main	@ALL	1
sandbox	@ALL	0
sandbox	@editor	2
sandbox	@moderator	1
sandbox:*	@moderator	16
sandbox:*	@editor	16
sandbox:*	@ALL	0
stats	@ALL	0
